@echo off
ECHO -------------------------------------------------------------
ECHO                            ATUREDE
ECHO
ECHO Copiando arquivos do drive C: para o F:
ECHO
ECHO                   origem : C:
ECHO                  destino : F: (rede)
ECHO
ECHO
ECHO                         (alterado por Daniel em 01/Jun/1996)
ECHO -------------------------------------------------------------
COPY C:\TENAX\*.DBF    F:\TENAX /V

ECHO --- ATUALIZADO ---   
