 SCE0600                Sistema de Controle de Estoque                     >AD<
 CR0600                        TENAX ACO E FERRO

  ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ Cadastro de Cheques ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
  ³                                                                          ³
  ³ Duplicata.:00000001 A                                                    ³
  ³ Emissao...:27/06/96     Vencimento...:          Valor...:                ³
  ³                                                                          ³
  ³ Bom Para..:02/07/96     Valor Cheque.:        666,17                     ³
  ³                                                                          ³
  ³ Banco.....:415 - NACIONAL                                                ³
  ³ Agencia...:0264   - VOLUNTARIOS DA PATRIA                                ³
  ³ Conta.....:00000000453                                                   ³
  ³ Nro.Cheque:00000000040                                                   ³
  ³ Cpf/cGc...:[C]   .   .   /    -                                          ³
  ³                                                                          ³
  ³ Cliente...:A1255  - A.M.                                                 ³
  ³ Telefone..: (    )   -                                                   ³
  ³                                                                          ³
  ³                                                                          ³
  ³ Destino...:JKSDFOGAHBEROJL;GBNRJ G                                       ³
  ³                                                                          ³
  ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ

 SCE1100                Sistema de Controle de Estoque                     >AD<
 CR1100                        TENAX ACO E FERRO

  ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ Baixa de Duplicatas ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿     > <F3> - Inclui / <F4> - Altera / <F5> - Exclui
  ³Duplicata Sq Cliente    Vencimento Pagamento Qtd.Ch  Valor                ³
  ³ÄÄÄÄÄÄÄÄÄÂÄÄÂÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÂÄÄÄÄÄÄÂÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ³
  ³00000000 ³  ³ALLUMAR   ³29/06/96  ³02       ³     0³             2,000.00 ³
  ³00000001 ³B ³SCHINDLER ³27/07/96  ³01       ³     0³               315.67 ³
  ³00000001 ³C ³SCHINDLER ³16/08/96  ³01       ³     0³               318.17 ³
  ³00000002 ³A ³MEC.SILFER³15/07/96  ³01       ³     0³             1,499.50 ³
  ³00000003 ³  ³ESTUB     ³27/06/96  ³05       ³     0³             1,260.00 ³
  ³00000004 ³  ³ALTAMIR   ³27/06/96  ³05       ³     0³             1,500.00 ³
  ³00000005 ³A ³A.R. DA SI³25/07/96  ³01       ³     0³               399.50 ³
  ³00000006 ³  ³A C M     ³27/06/96  ³05       ³     0³               500.00 ³
  ³00000007 ³  ³A.O.      ³27/06/96  ³02       ³     0³               600.00 ³
  ³00000008 ³  ³A B C     ³29/06/96  ³02       ³     0³             2,000.00 ³
  ³         ³  ³          ³          ³         ³      ³                      ³
  ³         ³  ³          ³          ³         ³      ³                      ³
  ³         ³  ³          ³          ³         ³      ³                      ³
  ³         ³  ³          ³          ³         ³      ³                      ³
  ÃÄÄÄÄÄÄÄÄÄÁÄÄÁÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÁÄÄÄÄÄÄÁÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´
  ³                                        Total Pendente...:      10.392,84 ³
  ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
   > <F4> - Recebe Duplicata