// Modos de liberacao de usuario

#COMMAND rt_prompt ( <lin>, <col>, <msg>[ , <cnt>] )  =>;
	   @ <lin>, <col> PROMPT <msg> [ MESSAGE <cnt> ]

#COMMAND say( <lin>, <col>, <msg> [, <pn>] )  =>;
	    @ <lin>, <col> SAY <msg> [ PICTURE <pn> ]

#COMMAND keyboard( <tecla> )  => keyboard <tecla>

#define C_INC	"IAS"
#define C_EXC	"AS"
#define C_ALT	"AS"
#define C_DEL	"AS"
#define C_CON	"IACS"
#define C_IMP	"IACS"

